### ISSUE TITLE
Fix grails dependency

### ISSUE THREAD

**Issue by paulovlobato** [vsachinv/grails-csv#6]
By using grails 3.x, to import the plugin, the compile should be:

`compile 'org.grails.plugins:csv:1.0.1'`

instead of

`compile 'org.grails.plugins:grails-csv:1.0.1'`

**Comment by vsachinv** [comment]
@paulovlobato Sorry! I guess i am alot late but now i have fixed the same. 
https://github.com/vsachinv/grails-csv/pull/10
