### ISSUE TITLE
Wrong repository key

### ISSUE THREAD

**Issue by wsdrools** [vsachinv/grails-csv#8]
The dependencies key for the plugin stated in your readme is not correct. 
Instead of 
compile 'org.grails.plugins:grails-csv:1.0.1'

It should be 
compile 'org.grails.plugins:csv:1.0.1'

Thanks for your plugin.

Regards,

WSCHIA

**Comment by vsachinv** [comment]
@wsdrools  Sorry! I guess i am alot late but now i have fixed the same https://github.com/vsachinv/grails-csv/pull/10 .
